### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by anaselmi** [benmoran56/esper#26]
Going into the actual reading the docstrings inside of methods could be replaced by actual documentation

**Comment by anaselmi** [comment]
imma just fork esper for now and pull request back here later

**Comment by benmoran56** [comment]
That would be fantastic. I've been meaning to do this for a while. The goal was to use sphinx-apidoc, or similar, to generate the API documentation from the docstrings. There are probably a few missing things in there, such as `:raises xxxxx:` and `:returns xxxx:`, but they should be fairly complete. 

The README is a start, but It is probably not all that useful to a beginner. Proper documentation with a few sections would be great to have eventually.

**Comment by anaselmi** [comment]
yeah. i have a big project for the next week, but when im done im going to get around to getting around to my first real open source contributions. still a bit new so let me know if anything needs fixing when i submit the eventual pull request. thanks

**Comment by benmoran56** [comment]
No worries. Please feel free to ask if you want to confirm anything before proceeding. 

I'm happy to consider most changes to Esper, as long as it fits within the scope of the project. Anything that has a legitimate use case, and won't cause a regression elsewhere.
