### ISSUE TITLE
Add a way to get new components and components pending deletion

### ISSUE THREAD

**Issue by Moguri** [benmoran56/esper#36]
When I use an ECS, I often find myself needing to perform some logic in the System/Processor when when a component is added or removed. For example, if a new `PhysicsComponent` is added to an entity, I may want to have a `PhysicsProcessor` add a physics object to a physics simulation.

I am currently looking at hacking up a `Processor` subclass to track which entities/components were processed on previous invocations of `process()` and figure out which entities are new or missing. Would there be interest in having something like this in Esper itself?

**Comment by benmoran56** [comment]
Hi Moguri, 
Sorry for the late reply to your issue ticket! I don't seem to be getting alerts for some reason, and missed the fact that I had an open ticket. 

About your question, entities that are deleted are not immediately deleted by default. They are added to a `_dead_entities` list, and deleted at the start of the next call to `World.process()`. (You can access this list at `World._dead_entities`). Would that satisfy your requirement? It's just a list if integers. If it's useful, I can expose that as a property that can be queried. If you need this information available on the next call to `process`, you could make a `RecordKeepingProcessor` that is the lowest priority (such as -1), which just makes a copy of this dead entity list. That way you can have them available at the next frame.

**Comment by Moguri** [comment]
I played around with this back when I posted this issue, and I was not able to figure out a reliable way to track new and deleted components. Processing just dead entities is not enough since a component can be removed from an entity without deleting the entity. Also, this does not address new components. In general, is looks like Esper intends this to be handled in constructors on components, which seems fine overall, but not what I would personally prefer.

[Here](https://github.com/Moguri/panda3d-simpleecs/blob/master/simpleecs/systems.py#L18) is an example of the kind of logic I would like to do for new and deleted components. This is from some ECS code (created before I found Esper) that I recently resurrected to play with APIs.

**Comment by benmoran56** [comment]
I wouldn't put any logic in the Component itself. In general if you need to track creation or deletion of specific Components, I would put that logic in the Processor/s that are doing the adding or deleting of components or entities. I wouldn't be too keen on adding additional tracking logic to esper itself, because the entity creation code path should be as fast as possible. Does that make sense?

**Comment by benmoran56** [comment]
I'm going to close this for now, but please reopen it or open a new issue if you want to follow up!
