### ISSUE TITLE
Upload a wheel for esper to PyPI

### ISSUE THREAD

**Issue by rdb** [benmoran56/esper#38]
It would be great if you could upload a wheel version of this package to PyPI, which will make it possible to use esper with packaging systems that only support wheels and not source distributions.  It should be as simple as:
```
python setup.py bdist_wheel
twine upload dist/esper-*.whl
```

**Comment by benmoran56** [comment]
Hi rdb, 

First of all, sorry for the slow reply. I haven't been getting new issue alerts! 
To be honest I wasn't aware that this could be an issue. I can certainly start uploading wheels as well. I'll see if I can get a point release out soon which contains wheels.

**Comment by benmoran56** [comment]
A new release is out, including wheels. Please let me know if you still have any issues!

**Comment by rdb** [comment]
Looks great, thanks so much!

**Comment by benmoran56** [comment]
No problem. I didn't even know this was an issue for people, so I'll be uploading wheels from now on.
