### ISSUE TITLE
Optimize using Cython

### ISSUE THREAD

**Issue by Pebaz** [benmoran56/esper#41]
I compiled Esper locally using Cython and experienced a mild speedup.

Perhaps the `setup.py` could look for Cython and if installed, compile Esper locally.

**Comment by benmoran56** [comment]
Hi @Pebaz,

I don't use Cython myself, but if you could point me towards an example of that I would be happy to look into it.

**Comment by benmoran56** [comment]
I'm going to close this for now, but if someone has more information please reopen!
