### ISSUE TITLE
"remove_component" and "delete_entity" are inconsistent

### ISSUE THREAD

**Issue by r1chardj0n3s** [benmoran56/esper#46]
It'd be nice if the verb as consistent.

**Comment by benmoran56** [comment]
I think in the first case, the intended meaning is "remove component *from entity*", whereas delete is just delete. 
What do you think would make more sense?

**Comment by r1chardj0n3s** [comment]
I've just found it difficult to remember that one is "remove" and the other is "delete" :)

**Comment by r1chardj0n3s** [comment]
BTW your little library has now enabled bees to shoot fireballs. I hope you're very pleased with yourself 😉

**Comment by benmoran56** [comment]
Github just refuses to send me alerts for this repo. Sorry for the lack of response. 
In any case, I'm really glad to see people making use of esper. It was really the library I wanted to use myself, that didn't exist.

**Comment by benmoran56** [comment]
I'm going to close this for now, but I'm certainly open to talking about this sort of thing.
