### ISSUE TITLE
get_components does not get entities in order (ascending order).

### ISSUE THREAD

**Issue by WestwoodForever** [benmoran56/esper#47]
get_components does not get entities in order (ascending order). How can I get it in order?

I created about 5000 entities, and the order is out of order after 3932. Trying again is the same result.

```
def process(self, *args, **kwargs):
    if self.entity == None:
        for ent, (foo, foo2) in self.world.get_components(Foo, Foo2):
            self.entity = ent
            break

    if self.entity != None:
        foo_func()
        self.world.delete_entity(self.entity)
        self.entity = None
```

result...
...(1~3929)
entity:3930
entity:3931
entity:3932
entity:4096
...

**Comment by benmoran56** [comment]
Sorry for the slow reply! 

This is normal behavior. Entity IDs are not intended to be ordered, and just happen to be semi-ordered due to the usage of ints.  If you really need ordering, you can do something like this, using `sorted`: 
```py
for e, vel in sorted(world.get_component(Velocity)):
   ...
```

**Comment by WestwoodForever** [comment]
Thank you! I'm a beginner in python, but it's simple.

**Comment by benmoran56** [comment]
No worries! I'll close this for now.
