### ISSUE TITLE
Depth of an image

### ISSUE THREAD

**Issue by MonkeyToiletLadder** [benmoran56/esper#49]
How would i use the depth in a renderable component?

**Comment by MonkeyToiletLadder** [comment]
becuase unless the entities are sorted properly i cant find a a way to use the depth index in a system

**Comment by benmoran56** [comment]
I'm not sure exactly what you mean. You want to sort entities by their ID, when querying?

**Comment by MonkeyToiletLadder** [comment]
How can i sort entities by depth or sort the access to entities by their depth.  Like when you want a rendering order for objects.  Youd give each entity a depth or a component that has depth.  In your current system their is no way to sort enitites by components.  But it may be posible to sort access to those entities in a class or system.

**Comment by benmoran56** [comment]
For ECS in general, you can't really rely on the entity id to be ordered. `esper` happens to use `int`s, but in other libraries a `uuid` might be used instead. 

That said, you can just wrap the entity query with a `sorted` call. For example: 
```py
for ent, (vel, rend) in sorted(world.get_components(Velocity, Renderable)):
   ....
```

For my personal projects I tend to use `pyglet` library. The rendering order is something that is handled by the library itself. I tend to make a `Renderable` object that just wraps a `pyglet` Sprite: 
```py
class Renderable:
    def __init__(self, sprite, etc):
        self.sprite = sprite
        self.etc = etc
```
The rendering order is handled by the specific `Group` and `Batch` that the Sprite belongs to, so it's handled outside of `esper`.

**Comment by benmoran56** [comment]
I'll close this for now due to age, but please follow up if you have more questions.
