### ISSUE TITLE
I know ECS is largely used for games, but can this specific library also work for database backed CRUD web apps?

### ISSUE THREAD

**Issue by simkimsia** [benmoran56/esper#52]

**Comment by benmoran56** [comment]
Hi, 

I've never heard of anyone using it in that way, but you certainly could.  Most of the queries are based around getting all entities (ids) that have specific components, but there are also queries to get components via the entity id.

The only thing it doesn't have included is any data persistence. Most games don't need to save the entire world state to disk, so it's left up to users to pick out and save whatever they need. If you _do_ need persistence, then you would need to handle that yourself.

**Comment by benmoran56** [comment]
Going to close this for now, but feel free to open a new ticket if you have any follow up questions.

**Comment by YAMLcase** [comment]
@simkimsia I too am looking to tinker with ECS pattern for non-game applications.  How has your experimentation gone?
