### ISSUE TITLE
`py.typed` file is missing.

### ISSUE THREAD

**Issue by HexDecimal** [benmoran56/esper#64]
This file is needed for [PEP 561](https://www.python.org/dev/peps/pep-0561/) to mark the package as type-hinted.  Without it the package isn't considered typed when installed as a package or from PyPI.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. Unfortunately it doesn't seem like it's currently possible for module-only libraries: 
> This PEP does not support distributing typing information as part of module-only distributions. The code should be refactored into a package-based distribution and indicate that the package supports typing as described above.

That's unfortunate, but I would prefer not to make `esper` into a package. Being a single-file library is something I really like about it. One of my goals was to allow users to just copy it into their project without necessarily needing to install it. 
Any ideas?

**Comment by HexDecimal** [comment]
A single package without dependencies isn't much more complex than a single module.  You would copy an `esper` directory instead of a `esper.py` file and you'd import it the exact same way.

**Comment by benmoran56** [comment]
`esper` actually was a package in the past, but was consolidated back to a single module due to some user demand.

If you wouldn't mind, could you explain what you mean by it "isn't considered typed" when installing from PyPi? 
Running `mypy` against the module seems to work fine without it. I had a look through the PEP, but couldn't really grasp it all. 
I guess my question is:  what is this breaking by not existing? 

Thanks in advance!

**Comment by HexDecimal** [comment]
When it's vendored then its fine, but when it's installed to `site-packages` then Mypy won't follow the import of it to look at its types, and you have to tell Mypy to ignore the import to continue.

Mypy will assume that local files are typed, but it needs stub-files or `py.typed` for an external package.

**Comment by benmoran56** [comment]
Thanks for the explaination. And also, thanks for the pull request. 
I can't say I'm happy about having to change it just for mypy, but I guess it can't be helped at the moment.
