### ISSUE TITLE
event handler as function

### ISSUE THREAD

**Issue by Felecarpp** [benmoran56/esper#69]
Hey ! Thanks for this greet library !
In the README.rst I can read: 

> An event handler can be **a function** or class method.

That works fine with methods but with functions I get this error:

```
Python 3.10.4 (main, Mar 25 2022, 19:56:11) [GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import esper
>>> def foo():
...     pass
... 
>>> esper.set_handler("foo", foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.10/site-packages/esper/__init__.py", line 79, in set_handl
er
    event_registry[name].add(_WeakMethod(func, _make_callback(name)))
  File "/usr/lib/python3.10/weakref.py", line 52, in __new__
    raise TypeError("argument should be a bound method, not {}"
TypeError: argument should be a bound method, not <class 'function'>
>>> 
```

**Comment by j-fdion** [comment]
`def set_handler(name: str, func) -> None:
    if name not in event_registry:
        event_registry[name] = set()

    if isinstance(func, types.MethodType):
        event_registry[name].add(_WeakMethod(func, _make_callback(name)))
    else:
        event_registry[name].add(_ref(func, _make_callback(name)))`

Testing if the function is a method type would fix the error.

**Comment by benmoran56** [comment]
Thanks for opening the ticket, and thanks for the suggestions j-fdion. I'll push out a fix shortly.

**Comment by benmoran56** [comment]
Looks like `isinstance` is about 45% faster, so lets go with that.

**Comment by benmoran56** [comment]
New 2.1 release was pushed out with the bugfix. Thanks!
