### ISSUE TITLE
enhance `get_component`

### ISSUE THREAD

**Issue by jason-bowen-zheng** [benmoran56/esper#70]
Read the following code:
```python
>>> import esper
>>> class Entity: pass
>>> class Animal(Entity): pass
>>> world = esper.World()
>>> world.create_entity(Entity())
1
>>> world.create_entity(Animal())
2
>>> world.get_component(Entity)
# a list has 1 item
>>> world.get_component(Animal)
# a list has 1 item
```

I want to use `esper` as the entities manager in a game. After I tried the above code, I think `get_component` should be: 
```python
>>> world.get_component(Entity)
# a list has 2 objects include an Entity and an Animal
>>> world.get_component(Animal)
# a list has 1 Animal object
```
which can return the inherited classes from given component.

I think the ECS may store not only the animal's position and its velocity but the whole animal, which is easy for designing the game.

**Comment by benmoran56** [comment]
No, that's not possible. It would be difficult to store in the DB, and difficult to query.

**Comment by benmoran56** [comment]
I'm going to close this for now, but please feel free to reply if you want to discuss further.
