### ISSUE TITLE
Try another ECS implementation - ecs_pattern library 

### ISSUE THREAD

**Issue by ikvk** [benmoran56/esper#73]
Try another ECS implementation - ecs_pattern library 
 
I wrote my own implementation of the ECS pattern:
https://github.com/ikvk/ecs_pattern
https://pypi.org/project/ecs-pattern/
And I used it to create an example: the Pong game.
The game uses pygame and my ecs_pattern library.
https://github.com/ikvk/ecs_pattern/tree/master/examples/pong

Try ecs_pattern in action!

===

Dear author of this lib, I hope for your understanding. No offense ;-)

**Comment by benmoran56** [comment]
Hi Vladimir,

No I don't mind. I'm happy to see more Python gamedev libraries.

If you like, I can put a link to your project in my README.

**Comment by ikvk** [comment]
I don't mind the link, thanks

**Comment by YAMLcase** [comment]
@ikvk I'm shopping for an ECS module, how is yours different from esper?  In my use case, I'm wanting to sandbox ECS patterns in non-games settings, specifically building a dashboard for system health by polling device hardware sensors.

**Comment by ikvk** [comment]
Compare python ECS libs: esper and ecs_pattern:
https://github.com/ikvk/ecs_pattern/tree/master/examples/compare_with_esper
