### ISSUE TITLE
Add a setup.py

### ISSUE THREAD

**Issue by SpotlightKid** [benmoran56/esper#8]
This would allow to:

* Upload the package to PyPI
* Automate unit tests with tox
* Install the package in a vitualenv
* etc.

I would create a PR, but I don't know how you like to organize the package metadata and what exactly to put for author, email, name etc.

**Comment by benmoran56** [comment]
Please go ahead and make a pull request, and I can modifiy it later if necessary. I don't have any strong preferences on the metadata layout.
