### ISSUE TITLE
`remove_component()` method removes entity if no more components left

### ISSUE THREAD

**Issue by gretkierewicz** [benmoran56/esper#82]
**Describe the bug**
As for Single Responsibility Principle remove component should do just that but it removes empty entity as well.
As I'm creating tests for my own project, I need to populate entity with some dummy component to prevent that and test cleaning another component logic.

**To Reproduce**
```python3
import esper

class Component:
    ...


world = esper.World()
entity = world.create_entity(Component())

assert world.entity_exists(entity=entity)

world.remove_component(entity=entity, component_type=Component)

assert world.entity_exists(entity=entity)  # AssertionError
```

**Expected behavior**
I assume that cleaning components should not clear entity. As removing and adding component should be independent from entity existence. Entity should be deleted by `delete_entity()` only and not under the hood so programmer has full control over it.

**Development environment:**
 - Python 3.11
 - Esper 2.4

**Additional context**
I will create unit tests for it and fix if approved for implementation

**Comment by benmoran56** [comment]
Hi Piotr,

Yes, please go ahead and remove that. I think this is leftover from the earlier code, and I never really thought about it. Thanks for opening the ticket.

**Comment by benmoran56** [comment]
Good question. That's pointless since the entity id is already known. 

Returning the entity instance could be useful, as long as it's not too expensive.
