### ISSUE TITLE
Add mypy to unit tests

### ISSUE THREAD

**Issue by benmoran56** [benmoran56/esper#84]
**Describe the addition or change you'd like to see.**
We should be running mypy or a similar type checker as part of the unit tests.

**Comment by gretkierewicz** [comment]
Yes this would be beneficial for understanding private attributes and how data is stored. Plus when refactoring it should be more secure to provide changes. How is should be implemented? I'm not into GitHub's pipelines

**Comment by benmoran56** [comment]
I went ahead and added it. There is a new job for mypy that uses the latest CPython releases only, since PyPy fails.
I think that should be plenty. 

Github pipelines always takes me a little trial and error, but they're not terribly difficult. It can get more annoying keeping up with the plugin updates though.
