### ISSUE TITLE
"Quick start" in README is targeting old version

### ISSUE THREAD

**Issue by joereynolds** [benmoran56/esper#92]
**Describe the bug**
I'm trying to get started with Esper and am bumping into errors around the no longer existing `World` method.

```
    self.world = esper.World()
AttributeError: module 'esper' has no attribute 'World'
```

What's the new recommended way of doing this?

**To Reproduce**
Use `esper.World()`

**Expected behavior**
The documentation to reflect the code and what's required

**Development environment:**
 - Python version 3.11
 - Esper version 3

**Comment by joereynolds** [comment]
I dug through the `example` dir and went from there. Did the trick!
Going to leave this open because I guess it still needs addressing.

I'll take a stab at it if I get the time soon

**Comment by benmoran56** [comment]
Hi Joe,
Thanks for opening the ticket. I must have missed these when updating the README. I'm glad the examples helped at least. 
I went through the README again, and I _think_ everything should be current now, but please let me know if you find anything strange (or even something that's not so clear).

**Comment by benmoran56** [comment]
Closing this as completed, but please feel free to follow up if necessary.
